services:
    waifuland_app:
        container_name: waifuland_fe_app_container
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env
        ports:
            - 4173:4173
