version: "3.1"
services:
  waifuland_app:
    container_name: waifuland_app_container
    image: dyallo/waifuland-fe
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    restart: always
    ports:
      - 3500:3500